### ISSUE TITLE
warning: dynamic exception specifications are deprecated in C++11

### ISSUE THREAD

**Issue by bogtroll** [didarmetu/Fibercoin#1]
Trying to compile the wallet and run into this error: warning: dynamic exception specifications are deprecated in C++11
Depricated in C++11 and made illegal in C++17.  I was compiling on Ubuntu 20 (about to go EoL) and even tried U18 (very much EoL) and get the same result.  Looks like there's something old in the code or one of the libraries being used.

Please can it be updted to compile on latest GCC?

**Comment by didarmetu** [comment]
Thanks for reporting this. You’re correct — the codebase contains legacy C++ constructs and dependencies that cause problems with modern GCC/OpenSSL/Boost toolchains.

I’m currently working on a modernization branch  specifically to bring Fibercoin up to date with newer build environments.

The work includes:

explicitly targeting the codebase’s intended C++11 standard so newer GCC versions don’t attempt to compile the legacy code as C++17+;
OpenSSL 3 compatibility, including replacing the legacy BIGNUM/BN_init implementation;
updated OpenSSL vs. LibreSSL detection;
Boost compatibility fixes;
fixes for existing compilation errors in the source;
a GitHub Actions build on Ubuntu 24.04 so compatibility is continuously tested with a current GCC/toolchain.

The Ubuntu 24.04 CI build is being tested now. Once the modernization branch builds cleanly and the changes are validated, I plan to merge it into the main branch.

I’ll keep this issue open until the current Linux build passes successfully. Thanks again for flagging it.
